### ISSUE TITLE
The new forsa-painter-geometrize.exe is identified as a virus by Windows Defender

### ISSUE THREAD

**Issue by FrostbiteXSW** [forza-painter/forza-painter#3]
Idk whether it is safe or not, but Windows Defender removed the exe file as soon as I tried to execute it. Do you have any idea why this happened?

**Comment by MekkaSiekka** [comment]
Which version of windows are you using?

**Comment by FrostbiteXSW** [comment]
Windows 10 Pro 21H2 19044.1387

**Comment by MekkaSiekka** [comment]
> Windows 10 Pro 21H2 19044.1387

Could you allow it in the defender? I did allow it and then I can run the geometrizer.

**Comment by FrostbiteXSW** [comment]
> > Windows 10 Pro 21H2 19044.1387
> 
> Could you allow it in the defender? I did allow it and then I can run the geometrizer.

Maybe it's the only solution to this problem for now, but I'll be appreciated if anyone can fix it. Anyway, thanks for your excellent work and your patience in dealing with my question.
