### ISSUE TITLE
Files not appearing

### ISSUE THREAD

**Issue by hza3als** [forza-painter/forza-painter#8]
When i download the file i cant find ( 1. drag_image_file_here.bat ) and ( 2. drag_geometry_json_here.bat ) files, can anyone help me find the solution please?]

**Comment by dedbeef** [comment]
These aren't in the new version. Read the readme or watch the updated tutorial.

**Comment by defineRaz** [comment]
Same problem at me, I drag the Image to create json files, then Its appear which one settings would I want to use, okey I choose for example 3 and It try to start process then It just stops as "pause" press -resume, but anything I press then the cmd just closes down.

**Comment by forza-painter** [comment]
New version doesn't use these bat files.
Please watch the video linked in the readme and consider joining the Discord.
