### ISSUE TITLE
Base square shape (used for masks on the edges) somewhat becomes a circle ?

### ISSUE THREAD

**Issue by SBRK** [forza-painter/forza-painter#9]
I've had this happen a few times. The final vinyl goup, instead of being square has a "pillow" shape. If I go all the way up and look at the mask shapes used for the borders, that are supposed to be squares, they do use the first (top left) vinyl shape available, but instead of being a square, it's a circle, somehow. Any idea what is happening here ? Is it a bug on Forza's end ?

**Comment by forza-painter** [comment]
This is simply a bug on the Forza side. Well, it's really a side effect of how I am setting the shape.
In older versions that still use masks you can save and load (I believe).
In newer versions masks are no longer used as it automatically adds a 1px border so this should be resolved now.
